version: 0.3

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - images/*
    - colors/*
    - css/*
    - fonts/*
    - js/*
    - php/*
    - projects/*