version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - css/*
    - images/*
    - fonts/*
    - js/*
    - php/*
    - projects/*
    - colors/*
    - dist/bundle.js